name: Python Tests

on: [push, pull_request]  # Runs on every push and pull request

jobs:
  test:
    runs-on: ubuntu-latest  # Run on latest Ubuntu

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Clone the repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Use Python 3.10

      - name: Install Dependencies
        run: |
          pip install pytest  # Install pytest

      - name: Run Tests
        run: pytest test_snake.py  # Run test script
